[package]
name = "sausage"
version = "0.1.0"
authors = ["zipper"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-unixfs = { path = "../rust-ipfs/unixfs" }
cid = "*"
anyhow = "*"